# Atelier Préparation de Données Tabulaires

Contexte Une entreprise exploite plusieurs bâtiments intelligents équipés de capteurs IoT. Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la qualité de l'air, la consommation énergétique, le nombre de personnes présentes, le type de bâtiment, le mode de fonctionnement et l'état du système de climatisation. Les données collectées sont destinées à alimenter ultérieurement un modèle de Machine Learning capable de prédire la consommation énergétique ou de détecter les situations anormales. Cependant, les données brutes présentent volontairement différents problèmes : valeurs manquantes, doublons, valeurs aberrantes, types incorrects, valeurs incohérentes, variables catégorielles, catégories rares, déséquilibre des classes et échelles différentes entre variables. L'objectif de l'atelier est donc de transformer le fichier brut en un jeu de données propre et prêt pour le Machine Learning.

## Partie 1 – Explorer les données

### 1) Charger les données CSV ;

In [2]:
import pandas as pd

df = pd.read_csv("../data/smart_building_raw.csv")

## 2) Afficher les premières lignes du dataset ;

In [3]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

## 3) Afficher les dernières lignes du dataset ;

In [4]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

## 4) Combien d'observations contient le dataset ?

In [5]:
print("Nombre d'observations :", df.shape[0])

Nombre d'observations : 507

## 5) Combien de variables possède le dataset ?

In [7]:
print("Nombre de variables :", df.shape[1])

Nombre de variables : 14

## 6) Identifier les variables numériques ;

In [ ]:
# df.select_dtypes(include='number') : selection tous les variables de types numerique
# .columns : recupere les noms de ces colonne sous forme de liste
variables_numeriques = df.select_dtypes(include='number').columns
print("Les variables numériques : ", list(variables_numeriques))

Les variables numériques :  ['id_mesure', 'temperature', 'humidite', 'co2', 'occupation', 'consommation_kwh']

## 7) Identifier les variables catégorielles ;

In [ ]:
# df.select_dtypes(include='number') : selection tous les variables de types texte (objet)
variables_categorielles = df.select_dtypes(include='str').columns
print("Les variables catégorielles : ", list(variables_categorielles))

Les variables catégorielles :  ['date', 'batiment', 'type_batiment', 'zone', 'mode_climatisation', 'etat_systeme', 'jour_semaine', 'alerte']

## 8) Identifier les dates

In [32]:
variables_dates = ['date']
print("variables de types dates : ", variables_dates)

variables de types dates :  ['date']

## 9) Identifier les identifiants

In [33]:
variables_identifiants = ['id_mesure']
print("variables de types identifiants : ", variables_identifiants)

variables de types identifiants :  ['id_mesure']

## 10) Déterminer les statistiques : moyenne, médiane, minimum, maximum, écart-type et quartiles.

In [36]:
df.describe()

,id_mesure,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,24.154141,57.864113,844.150000,44.850299,169.069323
std,144.782769,7.418465,16.026336,582.181386,24.949139,53.164294
min,1001.000000,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,96.000000,160.000000,6000.000000,116.000000,336.200000